resource "helm_release" "elasticsearch" {
  count      = var.deploy_efk ? 1 : 0
  name       = "elasticsearch"
  namespace  = kubernetes_namespace.logging[0].metadata[0].name
  repository = "https://charts.bitnami.com/bitnami"
  chart      = "elasticsearch"
  version    = "19.5.4"

  set = [
    {
      name  = "replicas"
      value = "1"
    },
    {
      name  = "persistence.enabled"
      value = "false"
    },
    {
      name  = "tls.autoGenerated"
      value = "true"
    }
  ]
}
