resource "helm_release" "elasticsearch" {
  count      = var.deploy_efk ? 1 : 0
  name       = "elasticsearch"
  namespace  = kubernetes_namespace.logging[0].metadata[0].name
  repository = "https://charts.bitnami.com/bitnami"
  chart      = "elasticsearch"
  version    = "19.5.4"

  timeout = 600

  set = [
    # Run only 1 master node — no data / ingest / coordination nodes
    {
      name  = "master.replicas"
      value = "1"
    },
    {
      name  = "data.replicas"
      value = "0"
    },
    {
      name  = "ingest.replicas"
      value = "0"
    },
    {
      name  = "coordinating.replicas"
      value = "0"
    },

    # No persistence in dev
    {
      name  = "persistence.enabled"
      value = "false"
    },

    # Auto-generate TLS + creds
    {
      name  = "tls.autoGenerated"
      value = "true"
    },

    # Reduce memory footprint to fit small nodes
    {
      name  = "resources.requests.memory"
      value = "512Mi"
    },
    {
      name  = "resources.limits.memory"
      value = "1Gi"
    }
  ]
}
