#!/usr/bin/env bash

RESOURCE_GROUP="${1:-flixtube}"
# Optional: specify namespace as the second argument
NAMESPACE="${2:-default}"

az aks get-credentials --resource-group "$RESOURCE_GROUP" --name "$RESOURCE_GROUP"

echo "Fetching pods in namespace: $NAMESPACE"
pods=$(kubectl get pods -n "$NAMESPACE" --no-headers -o custom-columns=":metadata.name")

for pod in $pods; do
  echo "--------------------------------------------"
  echo "Logs for pod: $pod"
  echo "--------------------------------------------"
  kubectl logs -n "$NAMESPACE" "$pod"
  echo
done
