#
# To deploy:
#
# kubectl apply -f scripts/deploy.yaml
#
#
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 3
  minReplicas: 3
  maxReplicas: 5
  selector:
    matchLabels:
      app: gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: $CONTAINER_REGISTRY/gateway:$VERSION
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "4000"
            - name: RABBIT
              value: amqp://test:test@rabbit:5672
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
